name: GringottsTowny
authors: [ nikosgram, GroobleDierne ]
website: https://github.com/nikosgram/gringotts-towny
version: ${project.version}
main: com.oglofus.gringotts.towny.GringottsTowny

api-version: "1.18"

depend: [ Gringotts, Towny ]