name: gringotts-towny
authors: [ nikosgram ]
website: https://github.com/nikosgram/gringotts-towny
version: ${version}
main: com.oglofus.gringotts.towny.GringottsTowny

awareness:
  - '!@UTF-8'

depend:
  - Gringotts
  - Towny

loadbefore:
  - Gringotts
