name: gringotts-towny
authors: [ nikosgram ]
website: https://github.com/nikosgram/gringotts-towny
version: ${version}
main: com.oglofus.gringotts.towny.GringottsTowny

api-version: "1.18"

awareness:
  - !@UTF-8

depend:
  - Gringotts
  - Towny